# Generated by Django 4.2.4 on 2023-08-23 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('composition', models.CharField(max_length=300, verbose_name='Состав')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Картинка')),
                ('assortment', models.BooleanField(default=True, verbose_name='В наличии')),
            ],
        ),
        migrations.CreateModel(
            name='BouquetOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('bouquet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flower_app.bouquet')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Повод')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('telegram', models.BigIntegerField(blank=True, verbose_name='Telegram id')),
                ('role', models.CharField(max_length=50, verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('bouquets', models.ManyToManyField(related_name='orders', through='flower_app.BouquetOrder', to='flower_app.bouquet')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='flower_app.client', verbose_name='клиент')),
            ],
        ),
        migrations.AddField(
            model_name='bouquetorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower_app.order'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower_app.reason'),
        ),
    ]
