# Generated by Django 4.2.4 on 2023-08-23 07:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Телефон'),
        ),
    ]
