# Generated by Django 4.2.4 on 2023-08-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0002_add_phone_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='telegram',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram id'),
        ),
    ]
