# Generated by Django 4.2.4 on 2023-08-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0003_fix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bouquet',
            options={'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='reason',
            options={'verbose_name': 'Повод', 'verbose_name_plural': 'Повод'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Персонал'},
        ),
    ]
