# Generated by Django 4.2.4 on 2023-08-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0004_alter_bouquet_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
