# Generated by Django 4.2.4 on 2023-08-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0005_bouquet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
