# Generated by Django 4.2.4 on 2023-08-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0007_alter_bouquet_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
