# Generated by Django 4.2.4 on 2023-08-24 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0010_add_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Временной интервал')),
            ],
            options={
                'verbose_name': 'Временной интервал',
                'verbose_name_plural': 'Временные интервалы',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='flower_app.deliverytimeslot'),
        ),
    ]
