# Generated by Django 4.2.4 on 2023-08-24 15:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0011_deliverytimeslot_order_delivery_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='flower_app.deliverytimeslot', verbose_name='Временной интервал'),
        ),
    ]
