# Generated by Django 4.2.4 on 2023-08-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0014_add_address_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес доставки'),
        ),
    ]
