# Generated by Django 4.2.4 on 2023-08-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0015_alter_order_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Ценовая категория')),
                ('min', models.IntegerField(blank=True, null=True, verbose_name='Минимальная цена')),
                ('max', models.IntegerField(blank=True, null=True, verbose_name='Максимальная цена')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
