# Generated by Django 4.2.4 on 2023-08-26 15:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0016_add_pricecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UN', 'Необработанный'), ('OK', 'Выполнен')], db_index=True, default='UN', max_length=2, verbose_name='статус')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
            },
        ),
        migrations.AlterModelOptions(
            name='pricecategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории цен'},
        ),
    ]
