# Generated by Django 4.2.4 on 2023-08-26 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0017_consultation_alter_pricecategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Заявка на консультацию', 'verbose_name_plural': 'Заявки на консультацию'},
        ),
        migrations.AddField(
            model_name='consultation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата подачи'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('UN', 'Необработана'), ('OK', 'Выполнена')], db_index=True, default='UN', max_length=2, verbose_name='статус'),
        ),
    ]
