# Generated by Django 4.2.4 on 2023-08-28 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0018_alter_consultation_options_consultation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='phone',
        ),
        migrations.AddField(
            model_name='consultation',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='flower_app.client', verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('UN', 'Не обработана'), ('OK', 'Выполнена')], db_index=True, default='UN', max_length=2, verbose_name='статус'),
        ),
    ]
